//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace MashupDesignTool.DataService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DesignedApplicationData", Namespace="http://schemas.datacontract.org/2004/07/WebServer.Web")]
    public partial class DesignedApplicationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ApplicationNameField;
        
        private System.Guid IdField;
        
        private System.DateTime LastUpdateField;
        
        private System.Guid UserIdField;
        
        private string XmlStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlString {
            get {
                return this.XmlStringField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlStringField, value) != true)) {
                    this.XmlStringField = value;
                    this.RaisePropertyChanged("XmlString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/GetDesignedApplicationList", ReplyAction="http://tempuri.org/IDataService/GetDesignedApplicationListResponse")]
        System.IAsyncResult BeginGetDesignedApplicationList(string userName, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> EndGetDesignedApplicationList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/Insert", ReplyAction="http://tempuri.org/IDataService/InsertResponse")]
        System.IAsyncResult BeginInsert(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState);
        
        MashupDesignTool.DataService.DesignedApplicationData EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/Update", ReplyAction="http://tempuri.org/IDataService/UpdateResponse")]
        System.IAsyncResult BeginUpdate(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState);
        
        MashupDesignTool.DataService.DesignedApplicationData EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/Delete", ReplyAction="http://tempuri.org/IDataService/DeleteResponse")]
        System.IAsyncResult BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        MashupDesignTool.DataService.DesignedApplicationData EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/GetDesignedApplication", ReplyAction="http://tempuri.org/IDataService/GetDesignedApplicationResponse")]
        System.IAsyncResult BeginGetDesignedApplication(System.Guid id, System.AsyncCallback callback, object asyncState);
        
        MashupDesignTool.DataService.DesignedApplicationData EndGetDesignedApplication(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/GetUserIdFromName", ReplyAction="http://tempuri.org/IDataService/GetUserIdFromNameResponse")]
        System.IAsyncResult BeginGetUserIdFromName(string userName, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndGetUserIdFromName(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : MashupDesignTool.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDesignedApplicationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDesignedApplicationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MashupDesignTool.DataService.DesignedApplicationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MashupDesignTool.DataService.DesignedApplicationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MashupDesignTool.DataService.DesignedApplicationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MashupDesignTool.DataService.DesignedApplicationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MashupDesignTool.DataService.DesignedApplicationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MashupDesignTool.DataService.DesignedApplicationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDesignedApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDesignedApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MashupDesignTool.DataService.DesignedApplicationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MashupDesignTool.DataService.DesignedApplicationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserIdFromNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserIdFromNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<MashupDesignTool.DataService.IDataService>, MashupDesignTool.DataService.IDataService {
        
        private BeginOperationDelegate onBeginGetDesignedApplicationListDelegate;
        
        private EndOperationDelegate onEndGetDesignedApplicationListDelegate;
        
        private System.Threading.SendOrPostCallback onGetDesignedApplicationListCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDesignedApplicationDelegate;
        
        private EndOperationDelegate onEndGetDesignedApplicationDelegate;
        
        private System.Threading.SendOrPostCallback onGetDesignedApplicationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserIdFromNameDelegate;
        
        private EndOperationDelegate onEndGetUserIdFromNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserIdFromNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDesignedApplicationListCompletedEventArgs> GetDesignedApplicationListCompleted;
        
        public event System.EventHandler<InsertCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<GetDesignedApplicationCompletedEventArgs> GetDesignedApplicationCompleted;
        
        public event System.EventHandler<GetUserIdFromNameCompletedEventArgs> GetUserIdFromNameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginGetDesignedApplicationList(string userName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDesignedApplicationList(userName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> MashupDesignTool.DataService.IDataService.EndGetDesignedApplicationList(System.IAsyncResult result) {
            return base.Channel.EndGetDesignedApplicationList(result);
        }
        
        private System.IAsyncResult OnBeginGetDesignedApplicationList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginGetDesignedApplicationList(userName, callback, asyncState);
        }
        
        private object[] OnEndGetDesignedApplicationList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndGetDesignedApplicationList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDesignedApplicationListCompleted(object state) {
            if ((this.GetDesignedApplicationListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDesignedApplicationListCompleted(this, new GetDesignedApplicationListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDesignedApplicationListAsync(string userName) {
            this.GetDesignedApplicationListAsync(userName, null);
        }
        
        public void GetDesignedApplicationListAsync(string userName, object userState) {
            if ((this.onBeginGetDesignedApplicationListDelegate == null)) {
                this.onBeginGetDesignedApplicationListDelegate = new BeginOperationDelegate(this.OnBeginGetDesignedApplicationList);
            }
            if ((this.onEndGetDesignedApplicationListDelegate == null)) {
                this.onEndGetDesignedApplicationListDelegate = new EndOperationDelegate(this.OnEndGetDesignedApplicationList);
            }
            if ((this.onGetDesignedApplicationListCompletedDelegate == null)) {
                this.onGetDesignedApplicationListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDesignedApplicationListCompleted);
            }
            base.InvokeAsync(this.onBeginGetDesignedApplicationListDelegate, new object[] {
                        userName}, this.onEndGetDesignedApplicationListDelegate, this.onGetDesignedApplicationListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginInsert(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MashupDesignTool.DataService.DesignedApplicationData MashupDesignTool.DataService.IDataService.EndInsert(System.IAsyncResult result) {
            return base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MashupDesignTool.DataService.DesignedApplicationData data = ((MashupDesignTool.DataService.DesignedApplicationData)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginInsert(data, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            MashupDesignTool.DataService.DesignedApplicationData retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndInsert(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new InsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(MashupDesignTool.DataService.DesignedApplicationData data) {
            this.InsertAsync(data, null);
        }
        
        public void InsertAsync(MashupDesignTool.DataService.DesignedApplicationData data, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        data}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginUpdate(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MashupDesignTool.DataService.DesignedApplicationData MashupDesignTool.DataService.IDataService.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MashupDesignTool.DataService.DesignedApplicationData data = ((MashupDesignTool.DataService.DesignedApplicationData)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginUpdate(data, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            MashupDesignTool.DataService.DesignedApplicationData retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(MashupDesignTool.DataService.DesignedApplicationData data) {
            this.UpdateAsync(data, null);
        }
        
        public void UpdateAsync(MashupDesignTool.DataService.DesignedApplicationData data, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        data}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MashupDesignTool.DataService.DesignedApplicationData MashupDesignTool.DataService.IDataService.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginDelete(id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            MashupDesignTool.DataService.DesignedApplicationData retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(System.Guid id) {
            this.DeleteAsync(id, null);
        }
        
        public void DeleteAsync(System.Guid id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginGetDesignedApplication(System.Guid id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDesignedApplication(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MashupDesignTool.DataService.DesignedApplicationData MashupDesignTool.DataService.IDataService.EndGetDesignedApplication(System.IAsyncResult result) {
            return base.Channel.EndGetDesignedApplication(result);
        }
        
        private System.IAsyncResult OnBeginGetDesignedApplication(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid id = ((System.Guid)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginGetDesignedApplication(id, callback, asyncState);
        }
        
        private object[] OnEndGetDesignedApplication(System.IAsyncResult result) {
            MashupDesignTool.DataService.DesignedApplicationData retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndGetDesignedApplication(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDesignedApplicationCompleted(object state) {
            if ((this.GetDesignedApplicationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDesignedApplicationCompleted(this, new GetDesignedApplicationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDesignedApplicationAsync(System.Guid id) {
            this.GetDesignedApplicationAsync(id, null);
        }
        
        public void GetDesignedApplicationAsync(System.Guid id, object userState) {
            if ((this.onBeginGetDesignedApplicationDelegate == null)) {
                this.onBeginGetDesignedApplicationDelegate = new BeginOperationDelegate(this.OnBeginGetDesignedApplication);
            }
            if ((this.onEndGetDesignedApplicationDelegate == null)) {
                this.onEndGetDesignedApplicationDelegate = new EndOperationDelegate(this.OnEndGetDesignedApplication);
            }
            if ((this.onGetDesignedApplicationCompletedDelegate == null)) {
                this.onGetDesignedApplicationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDesignedApplicationCompleted);
            }
            base.InvokeAsync(this.onBeginGetDesignedApplicationDelegate, new object[] {
                        id}, this.onEndGetDesignedApplicationDelegate, this.onGetDesignedApplicationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MashupDesignTool.DataService.IDataService.BeginGetUserIdFromName(string userName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserIdFromName(userName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Guid MashupDesignTool.DataService.IDataService.EndGetUserIdFromName(System.IAsyncResult result) {
            return base.Channel.EndGetUserIdFromName(result);
        }
        
        private System.IAsyncResult OnBeginGetUserIdFromName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            return ((MashupDesignTool.DataService.IDataService)(this)).BeginGetUserIdFromName(userName, callback, asyncState);
        }
        
        private object[] OnEndGetUserIdFromName(System.IAsyncResult result) {
            System.Guid retVal = ((MashupDesignTool.DataService.IDataService)(this)).EndGetUserIdFromName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserIdFromNameCompleted(object state) {
            if ((this.GetUserIdFromNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserIdFromNameCompleted(this, new GetUserIdFromNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserIdFromNameAsync(string userName) {
            this.GetUserIdFromNameAsync(userName, null);
        }
        
        public void GetUserIdFromNameAsync(string userName, object userState) {
            if ((this.onBeginGetUserIdFromNameDelegate == null)) {
                this.onBeginGetUserIdFromNameDelegate = new BeginOperationDelegate(this.OnBeginGetUserIdFromName);
            }
            if ((this.onEndGetUserIdFromNameDelegate == null)) {
                this.onEndGetUserIdFromNameDelegate = new EndOperationDelegate(this.OnEndGetUserIdFromName);
            }
            if ((this.onGetUserIdFromNameCompletedDelegate == null)) {
                this.onGetUserIdFromNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserIdFromNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserIdFromNameDelegate, new object[] {
                        userName}, this.onEndGetUserIdFromNameDelegate, this.onGetUserIdFromNameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MashupDesignTool.DataService.IDataService CreateChannel() {
            return new DataServiceClientChannel(this);
        }
        
        private class DataServiceClientChannel : ChannelBase<MashupDesignTool.DataService.IDataService>, MashupDesignTool.DataService.IDataService {
            
            public DataServiceClientChannel(System.ServiceModel.ClientBase<MashupDesignTool.DataService.IDataService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetDesignedApplicationList(string userName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userName;
                System.IAsyncResult _result = base.BeginInvoke("GetDesignedApplicationList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> EndGetDesignedApplicationList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData> _result = ((System.Collections.ObjectModel.ObservableCollection<MashupDesignTool.DataService.DesignedApplicationData>)(base.EndInvoke("GetDesignedApplicationList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsert(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public MashupDesignTool.DataService.DesignedApplicationData EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                MashupDesignTool.DataService.DesignedApplicationData _result = ((MashupDesignTool.DataService.DesignedApplicationData)(base.EndInvoke("Insert", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(MashupDesignTool.DataService.DesignedApplicationData data, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = data;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public MashupDesignTool.DataService.DesignedApplicationData EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                MashupDesignTool.DataService.DesignedApplicationData _result = ((MashupDesignTool.DataService.DesignedApplicationData)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(System.Guid id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public MashupDesignTool.DataService.DesignedApplicationData EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                MashupDesignTool.DataService.DesignedApplicationData _result = ((MashupDesignTool.DataService.DesignedApplicationData)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDesignedApplication(System.Guid id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetDesignedApplication", _args, callback, asyncState);
                return _result;
            }
            
            public MashupDesignTool.DataService.DesignedApplicationData EndGetDesignedApplication(System.IAsyncResult result) {
                object[] _args = new object[0];
                MashupDesignTool.DataService.DesignedApplicationData _result = ((MashupDesignTool.DataService.DesignedApplicationData)(base.EndInvoke("GetDesignedApplication", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserIdFromName(string userName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userName;
                System.IAsyncResult _result = base.BeginInvoke("GetUserIdFromName", _args, callback, asyncState);
                return _result;
            }
            
            public System.Guid EndGetUserIdFromName(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Guid _result = ((System.Guid)(base.EndInvoke("GetUserIdFromName", _args, result)));
                return _result;
            }
        }
    }
}
